// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: protoBuf/server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Value       string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ConfirmedAt int64  `protobuf:"varint,3,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	OptOut      bool   `protobuf:"varint,4,opt,name=opt_out,json=optOut,proto3" json:"opt_out,omitempty"`
}

func (x *EMail) Reset() {
	*x = EMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoBuf_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMail) ProtoMessage() {}

func (x *EMail) ProtoReflect() protoreflect.Message {
	mi := &file_protoBuf_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMail.ProtoReflect.Descriptor instead.
func (*EMail) Descriptor() ([]byte, []int) {
	return file_protoBuf_server_proto_rawDescGZIP(), []int{0}
}

func (x *EMail) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *EMail) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EMail) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

func (x *EMail) GetOptOut() bool {
	if x != nil {
		return x.OptOut
	}
	return false
}

type CreateEMailReQuest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CreateEMailReQuest) Reset() {
	*x = CreateEMailReQuest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoBuf_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEMailReQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEMailReQuest) ProtoMessage() {}

func (x *CreateEMailReQuest) ProtoReflect() protoreflect.Message {
	mi := &file_protoBuf_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEMailReQuest.ProtoReflect.Descriptor instead.
func (*CreateEMailReQuest) Descriptor() ([]byte, []int) {
	return file_protoBuf_server_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEMailReQuest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetEMailReQuest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetEMailReQuest) Reset() {
	*x = GetEMailReQuest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoBuf_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEMailReQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEMailReQuest) ProtoMessage() {}

func (x *GetEMailReQuest) ProtoReflect() protoreflect.Message {
	mi := &file_protoBuf_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEMailReQuest.ProtoReflect.Descriptor instead.
func (*GetEMailReQuest) Descriptor() ([]byte, []int) {
	return file_protoBuf_server_proto_rawDescGZIP(), []int{2}
}

func (x *GetEMailReQuest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetEMailBatchReQuest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Page  int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetEMailBatchReQuest) Reset() {
	*x = GetEMailBatchReQuest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoBuf_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEMailBatchReQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEMailBatchReQuest) ProtoMessage() {}

func (x *GetEMailBatchReQuest) ProtoReflect() protoreflect.Message {
	mi := &file_protoBuf_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEMailBatchReQuest.ProtoReflect.Descriptor instead.
func (*GetEMailBatchReQuest) Descriptor() ([]byte, []int) {
	return file_protoBuf_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetEMailBatchReQuest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetEMailBatchReQuest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type UpDateEMailReQuest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EMail *EMail `protobuf:"bytes,1,opt,name=eMail,proto3" json:"eMail,omitempty"`
}

func (x *UpDateEMailReQuest) Reset() {
	*x = UpDateEMailReQuest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoBuf_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpDateEMailReQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpDateEMailReQuest) ProtoMessage() {}

func (x *UpDateEMailReQuest) ProtoReflect() protoreflect.Message {
	mi := &file_protoBuf_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpDateEMailReQuest.ProtoReflect.Descriptor instead.
func (*UpDateEMailReQuest) Descriptor() ([]byte, []int) {
	return file_protoBuf_server_proto_rawDescGZIP(), []int{4}
}

func (x *UpDateEMailReQuest) GetEMail() *EMail {
	if x != nil {
		return x.EMail
	}
	return nil
}

type DeleteEMailReQuest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DeleteEMailReQuest) Reset() {
	*x = DeleteEMailReQuest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoBuf_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEMailReQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEMailReQuest) ProtoMessage() {}

func (x *DeleteEMailReQuest) ProtoReflect() protoreflect.Message {
	mi := &file_protoBuf_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEMailReQuest.ProtoReflect.Descriptor instead.
func (*DeleteEMailReQuest) Descriptor() ([]byte, []int) {
	return file_protoBuf_server_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEMailReQuest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EMail *EMail `protobuf:"bytes,1,opt,name=eMail,proto3,oneof" json:"eMail,omitempty"`
}

func (x *EMailResponse) Reset() {
	*x = EMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoBuf_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMailResponse) ProtoMessage() {}

func (x *EMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoBuf_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMailResponse.ProtoReflect.Descriptor instead.
func (*EMailResponse) Descriptor() ([]byte, []int) {
	return file_protoBuf_server_proto_rawDescGZIP(), []int{6}
}

func (x *EMailResponse) GetEMail() *EMail {
	if x != nil {
		return x.EMail
	}
	return nil
}

type EMailBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EMails []*EMail `protobuf:"bytes,1,rep,name=eMails,proto3" json:"eMails,omitempty"`
}

func (x *EMailBatchResponse) Reset() {
	*x = EMailBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoBuf_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EMailBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMailBatchResponse) ProtoMessage() {}

func (x *EMailBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoBuf_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMailBatchResponse.ProtoReflect.Descriptor instead.
func (*EMailBatchResponse) Descriptor() ([]byte, []int) {
	return file_protoBuf_server_proto_rawDescGZIP(), []int{7}
}

func (x *EMailBatchResponse) GetEMails() []*EMail {
	if x != nil {
		return x.EMails
	}
	return nil
}

var File_protoBuf_server_proto protoreflect.FileDescriptor

var file_protoBuf_server_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69,
	0x0a, 0x05, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x6f, 0x70, 0x74, 0x4f, 0x75, 0x74, 0x22, 0x2a, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x45, 0x4d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x40,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x22, 0x38, 0x0a, 0x12, 0x55, 0x70, 0x44, 0x61, 0x74, 0x65, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x4d,
	0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x22, 0x2a, 0x0a, 0x12, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x42, 0x0a, 0x0d, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x65, 0x4d, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x4d, 0x61, 0x69, 0x6c, 0x48, 0x00, 0x52, 0x05, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x88, 0x01, 0x01,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x22, 0x3a, 0x0a, 0x12, 0x45, 0x4d,
	0x61, 0x69, 0x6c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x06, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x06,
	0x65, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x32, 0xe1, 0x02, 0x0a, 0x12, 0x4d, 0x61, 0x69, 0x6c, 0x69,
	0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x45, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x4d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0b, 0x55, 0x70, 0x44, 0x61, 0x74, 0x65,
	0x45, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70,
	0x44, 0x61, 0x74, 0x65, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x6d, 0x61,
	0x69, 0x6c, 0x69, 0x6e, 0x67, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoBuf_server_proto_rawDescOnce sync.Once
	file_protoBuf_server_proto_rawDescData = file_protoBuf_server_proto_rawDesc
)

func file_protoBuf_server_proto_rawDescGZIP() []byte {
	file_protoBuf_server_proto_rawDescOnce.Do(func() {
		file_protoBuf_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoBuf_server_proto_rawDescData)
	})
	return file_protoBuf_server_proto_rawDescData
}

var file_protoBuf_server_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protoBuf_server_proto_goTypes = []any{
	(*EMail)(nil),                // 0: proto.EMail
	(*CreateEMailReQuest)(nil),   // 1: proto.CreateEMailReQuest
	(*GetEMailReQuest)(nil),      // 2: proto.GetEMailReQuest
	(*GetEMailBatchReQuest)(nil), // 3: proto.GetEMailBatchReQuest
	(*UpDateEMailReQuest)(nil),   // 4: proto.UpDateEMailReQuest
	(*DeleteEMailReQuest)(nil),   // 5: proto.DeleteEMailReQuest
	(*EMailResponse)(nil),        // 6: proto.EMailResponse
	(*EMailBatchResponse)(nil),   // 7: proto.EMailBatchResponse
}
var file_protoBuf_server_proto_depIdxs = []int32{
	0, // 0: proto.UpDateEMailReQuest.eMail:type_name -> proto.EMail
	0, // 1: proto.EMailResponse.eMail:type_name -> proto.EMail
	0, // 2: proto.EMailBatchResponse.eMails:type_name -> proto.EMail
	1, // 3: proto.MailingListService.CreateEMail:input_type -> proto.CreateEMailReQuest
	2, // 4: proto.MailingListService.GetEMail:input_type -> proto.GetEMailReQuest
	3, // 5: proto.MailingListService.GetEMailBatch:input_type -> proto.GetEMailBatchReQuest
	4, // 6: proto.MailingListService.UpDateEMail:input_type -> proto.UpDateEMailReQuest
	5, // 7: proto.MailingListService.DeleteEMail:input_type -> proto.DeleteEMailReQuest
	6, // 8: proto.MailingListService.CreateEMail:output_type -> proto.EMailResponse
	6, // 9: proto.MailingListService.GetEMail:output_type -> proto.EMailResponse
	7, // 10: proto.MailingListService.GetEMailBatch:output_type -> proto.EMailBatchResponse
	6, // 11: proto.MailingListService.UpDateEMail:output_type -> proto.EMailResponse
	6, // 12: proto.MailingListService.DeleteEMail:output_type -> proto.EMailResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protoBuf_server_proto_init() }
func file_protoBuf_server_proto_init() {
	if File_protoBuf_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoBuf_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoBuf_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateEMailReQuest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoBuf_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetEMailReQuest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoBuf_server_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetEMailBatchReQuest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoBuf_server_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpDateEMailReQuest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoBuf_server_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteEMailReQuest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoBuf_server_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*EMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoBuf_server_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*EMailBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protoBuf_server_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoBuf_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoBuf_server_proto_goTypes,
		DependencyIndexes: file_protoBuf_server_proto_depIdxs,
		MessageInfos:      file_protoBuf_server_proto_msgTypes,
	}.Build()
	File_protoBuf_server_proto = out.File
	file_protoBuf_server_proto_rawDesc = nil
	file_protoBuf_server_proto_goTypes = nil
	file_protoBuf_server_proto_depIdxs = nil
}